# Тема “Вычисления с помощью Numpy”
## Задание 1

In [1]:
import numpy as np

In [13]:
# Создаем массив a, вариантов создания много, но я остановился на таком
a = np.array([1, 2, 3, 3, 1, 6, 8, 11, 10, 7])

In [14]:
# приводим массив к виду, сформулированному в задании: 2 столбца по 5 элементов. Для чего меняем его форму и транспонируем
b = a.reshape(2,5).T
# Смотрим что получилось. То, что нужно.
b

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [18]:
# ищем среднее столбцов, что соотвествует оси = 0, остальные параметры функции, судя по докуметации, не нужны
mean_a = np.mean(b, axis = 0)
mean_a

array([2. , 8.4])

## Задание 2

In [20]:
# Отнимаем от каждого значения массивая b полученные средние значения
a_centered = b - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 3 

In [38]:
# Находим скалаярное произведение столбцов массива a_centered, сами столбцы извлекаем срезами
a_centered_sp = np.dot(a_centered[:,0],a_centered[:,1])
a_centered_sp

8.0

In [52]:
# делим его количество наблюдений минус один
a_centered_sp / (b.shape[0] - 1)


2.0

## Задание 4 

In [71]:
b[:,0]

array([1, 2, 3, 3, 1])

In [73]:
b[:,1]

array([ 6,  8, 11, 10,  7])

In [76]:
np.cov(b[:,0],b[:,1])[0][1]

2.0

In [88]:
# Мой массив b - это транспонированный массив а, соотвествующий условию задачи, поэтому мне надо его еще раз транспонировать. Но обращаю внимание методиста на то, что в задании 1 нет требования назвать нужный массив "а"
np.cov(b.T)[0][1]

2.0

# Тема “Работа с данными в Pandas”
## Задание 1

In [2]:
import pandas as pd

In [60]:
# Заполняем первый словарь данными из условия задачи, передаем его в DataFrame
data_list_1 = {
    'author_id':[1, 2, 3],
    'author_name':['Тургенев', 'Чехов', 'Островский']
}
authors = pd.DataFrame(data_list_1)
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [61]:
# Заполняем второй словарь данными из условия задачи, передаем его в DataFrame
data_list_2 = {
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price': [450, 300, 350, 500, 450, 370, 290]
}
book = pd.DataFrame(data_list_2)
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

# Задание 2

In [42]:
# Соединяем датафреймы через метод "merge" по полю "author_id" с параметром "outer", т.к. нам нужны все значения
authors_price = pd.merge(authors, book, on = 'author_id', how = 'outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

## Задание 3

In [43]:
# Выводим топ 5 цен
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

## Задание 4 

In [44]:
# Группируем данные по столбцу 'author_name' и используя метод "agg" по столбцу "price" ищем 'min', 'max', 'mean'
authors_stat = authors_price.groupby('author_name').agg({'price':['min', 'max', 'mean']})
authors_stat

price                 
              min  max        mean
author_name                       
Островский    290  370  330.000000
Тургенев      300  450  366.666667
Чехов         450  500  475.000000

In [46]:
# Переименовываем столбцы
authors_stat = authors_stat.rename(columns={'min': 'min_price', 'max': 'max_price', 'mean':' mean_price'})
authors_stat

price                      
            min_price max_price  mean_price
author_name                                
Островский        290       370  330.000000
Тургенев          300       450  366.666667
Чехов             450       500  475.000000

## Задание 5

In [51]:
# добавляем столбец 'cover' в authors_price
cover = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price['cover'] = cover
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [53]:
# импортируем numpy для метода sum и испольуем сводные табилца для заданного датафрейма
import numpy as np
book_info = pd.pivot_table(authors_price, values='price', index = ['author_name'], columns=['cover'], aggfunc = np.sum)
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      NaN
Тургенев      650.0    450.0
Чехов           NaN    950.0

In [54]:
# Заполняем пропуски нулями
book_info['мягкая'] = book_info['мягкая'].fillna(0)
book_info['твердая'] = book_info['твердая'].fillna(0)
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0

In [56]:
# пишем в пикл наш датафрейм
book_info.to_pickle('book_info.pkl')

In [58]:
# Читаем из файла пикл в новый датафрейм
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0

In [59]:
# Прверяем на иденитчность
book_info.equals(book_info2)

True